services:
  - type: web
    name: insider-tracker-backend
    runtime: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: secapi.api.key
        value: ${secapi_api_key}
      - key: finnhub.api.key
        value: ${finnhub_api_key}