services:
  - type: web
    name: insider-tracker-backend
    runtime: java
    rootDir: backend
    buildCommand: "./gradlew build -x test"
    startCommand: "java -jar build/libs/backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: secapi.api.key
        value: ${secapi_api_key}
      - key: finnhub.api.key
        value: ${finnhub_api_key}